sequenceDiagram
CLIENT->>SERVER : HTTP GET https://studies.cs.helsinki.fi/exampleapp/spa
Note over CLIENT : This client is Tanmay's Laptop
Note over SERVER : Requesting for data from the server
SERVER-->>CLIENT : HTML CODE FILE(STRUCTURE OF WEB-PAGE)
CLIENT->>SERVER : HTTP GET https://studies.cs.helsinki.fi/exampleapp/main.css
SERVER -->> CLIENT : CSS CODE FILE(main.css)
CLIENT ->> SERVER : HTTP GET https://studies.cs.helsinki.fi/exampleapp/spa.js
SERVER -->> CLIENT : JS CODE FILE(spa.js)
Note over CLIENT : Now the js file start executing and it request for data.json
CLIENT ->> SERVER : HTTP GET https://studies.cs.helsinki.fi/exampleapp/data.json
SERVER -->> CLIENT : JSON CODE FILE(data.json)
Note over CLIENT : Browser executes the event handler that render the notes to display
